# Check Supabase Function Logs for OpenRouter Debug Info

echo "🔍 Check your Supabase Dashboard logs for debug information:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/prmjtsiyeovmkujtbjwi"
echo "2. Navigate to: Edge Functions > analyze-war-intel > Logs"
echo "3. Look for recent entries with these debug messages:"
echo "   - '🔑 OpenRouter key found: sk-or-...' (shows first 10 chars)"
echo "   - Available env vars list"
echo "   - OpenRouter API response details"
echo ""
echo "4. If no logs appear, the function might not be reaching the AI analysis"
echo "   Look for: 'War content check result: true'"
echo ""
echo "5. Common issues to check in logs:"
echo "   - Key format (should start with sk-or-v1-)"
echo "   - Missing environment variables"
echo "   - Network/timeout errors"
echo ""
echo "📋 Next steps based on what you see in logs:"
echo "   - If key not found: Re-set with correct format"
echo "   - If key wrong format: Get new key from OpenRouter"
echo "   - If network error: Check OpenRouter service status"