# How to find the AI confidence score

echo "🔍 To see the AI confidence score:"
echo ""
echo "1. Go to Supabase Dashboard:"
echo "   https://supabase.com/dashboard/project/prmjtsiyeovmkujtbjwi"
echo ""
echo "2. Navigate to: Edge Functions > analyze-war-intel > Logs"
echo ""
echo "3. Look for these specific log messages in the recent entries:"
echo "   ⏭️ Low confidence (45%): \"Watch: The US has joined...\""
echo "   OR"
echo "   ✅ War event: airstrike in Ukraine (85%)"
echo ""
echo "4. The confidence score shows how certain the AI is about the war event"
echo "   - Below 60%: Article gets filtered out (event=null)"
echo "   - Above 60%: War event gets created and saved"
echo ""
echo "5. If you don't see confidence messages, the AI might have failed to parse"
echo "   Look for: ❌ JSON parse failed: [AI response]"
echo ""
echo "🔧 To see more detail, we can add extra logging to show the raw AI response"