# Reset article and test fixed JSON parser

echo "1. Reset the article to test the fixed JSON parsing:"
echo "UPDATE rss_articles SET is_processed = false WHERE id = '626ab425-89c7-477c-8800-092aed9be454';"
echo ""
echo "2. Run this SQL in Supabase, then test:"
echo ""
echo "curl -X POST https://prmjtsiyeovmkujtbjwi.supabase.co/functions/v1/analyze-war-intel \\"
echo "-H \"Content-Type: application/json\" \\"
echo "-H \"Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBybWp0c2l5ZW92bWt1anRiandpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjMyMzUsImV4cCI6MjA2NjEzOTIzNX0.lqv_1rW2P_2O0PH8cn15wMXoueZT8o_HQ5bm1bfk6cM\" \\"
echo "-d '{\"article_id\": \"626ab425-89c7-477c-8800-092aed9be454\"}'"
echo ""
echo "Expected: The fixed JSON parser should now extract the 75% confidence airstrike"
echo "and create a real war event instead of returning null!"
echo ""
echo "The AI previously found:"
echo "- event_type: airstrike"
echo "- country: Iran" 
echo "- source_country: United States"
echo "- confidence: 75%"
echo "- threat_level: medium"