[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.services.backend]
buildCommand = "npm install"
startCommand = "npm start"

[environments.production.services.frontend]
buildCommand = "npm run build"
startCommand = "npm run preview"
