[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environment]
# Railway will automatically set PORT - don't override it
NODE_ENV = { default = "production" }
RAILWAY_ENVIRONMENT = { default = "true" }
FRONTEND_URL = { default = "https://war-tracker-frontend.netlify.app" }
